on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'

      - name: dependency-installing
        run: |
          npm i

      - name: deploying
        env: 
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          npm run build
          npm run deploy
